# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "#HackWinter"
email: hweber@codeforamerica.org
description: > # this means to ignore newlines until "baseurl:"
  #HackWinter is a winter-focused app challenge, aimed at developing solutions that can help our communities deal with the challenges of living with freezing cold, darkness, and ice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hackwinter.github.io" # the base hostname & protocol for your site
twitter_username: hashtag/hackwinter
github_username:  hackwinter
collections:
- projects

# Build settings
markdown: kramdown
